"""Regenerate pathfinder3/calibration/report.md from verdicts and labels.

Reads ``calibration_pairs.jsonl`` (judge verdicts) and, when present and
filled in, ``labels_curator.jsonl`` (binary curator labels per axis). Before
labels exist the report covers what is computable without them: stratum
counts, per-stratum score distributions per judge, cheap/strong agreement,
and contract-failure counts. Once labels are in, it adds confusion matrices,
Cohen's kappa per axis (judge scores binarised at 0.5), AUC per axis, the
threshold sweep on s = corr * int with the flagged-share cap, and Wilson
intervals next to every rate, per plan item 4.

The report is generated, never hand-edited.

Usage: python3 pathfinder3/scripts/calibration_report.py
"""
from __future__ import annotations

import json
import math
from collections import defaultdict
from datetime import date

from _common import P3, PROMPT_VERSION, load_jsonl

PAIRS_PATH = P3 / "calibration" / "calibration_pairs.jsonl"
LABELS_PATH = P3 / "calibration" / "labels_curator.jsonl"
REPORT_PATH = P3 / "calibration" / "report.md"
RECALL_TARGET = 0.95
FLAG_SHARE_CAP = 0.10
STRATA = ("likely_good", "surface_similar", "hard_positive", "random")


def wilson(successes: int, n: int, z: float = 1.96) -> tuple[float, float]:
    if n == 0:
        return (0.0, 1.0)
    p = successes / n
    denom = 1 + z * z / n
    centre = (p + z * z / (2 * n)) / denom
    half = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / denom
    return (max(0.0, centre - half), min(1.0, centre + half))


def kappa(pairs: list[tuple[int, int]]) -> float | None:
    n = len(pairs)
    if n == 0:
        return None
    po = sum(1 for a, b in pairs if a == b) / n
    pa1 = sum(a for a, _ in pairs) / n
    pb1 = sum(b for _, b in pairs) / n
    pe = pa1 * pb1 + (1 - pa1) * (1 - pb1)
    if pe == 1:
        return None
    return (po - pe) / (1 - pe)


def auc(scored: list[tuple[float, int]]) -> float | None:
    pos = [s for s, y in scored if y == 1]
    neg = [s for s, y in scored if y == 0]
    if not pos or not neg:
        return None
    wins = sum(1 for sp in pos for sn in neg if sp > sn)
    ties = sum(0.5 for sp in pos for sn in neg if sp == sn)
    return (wins + ties) / (len(pos) * len(neg))


def fmt_ci(successes: int, n: int) -> str:
    if n == 0:
        return "n/a"
    lo, hi = wilson(successes, n)
    return f"{successes / n:.3f} [{lo:.3f}, {hi:.3f}] ({successes}/{n})"


def main() -> None:
    pairs = load_jsonl(PAIRS_PATH)
    verdict_of = {}
    for row in pairs:
        for v in row["verdicts"]:
            if v["prompt_version"] == PROMPT_VERSION:
                verdict_of[(row["pair_id"], v["tier"])] = v

    labels = {}
    if LABELS_PATH.exists():
        for row in load_jsonl(LABELS_PATH):
            if row.get("corr_label") is not None and row.get("int_label") is not None:
                labels[row["pair_id"]] = row

    lines = [
        "# Pathfinder3 calibration report",
        "",
        f"Generated by `calibration_report.py` on {date.today().isoformat()}; "
        "do not hand-edit.",
        "",
        f"Pairs: {len(pairs)}. Curator labels: {len(labels)} of {len(pairs)}.",
        "",
    ]

    lines += ["## Stratum counts", "", "| stratum | pairs | cheap judged | strong judged |",
              "|---|---|---|---|"]
    by_stratum = defaultdict(list)
    for row in pairs:
        by_stratum[row["stratum"]].append(row)
    for s in STRATA:
        rows = by_stratum.get(s, [])
        c = sum(1 for r in rows if (r["pair_id"], "cheap") in verdict_of)
        g = sum(1 for r in rows if (r["pair_id"], "strong") in verdict_of)
        lines.append(f"| {s} | {len(rows)} | {c} | {g} |")
    lines.append("")

    lines += ["## Score distributions (mean corr / mean int / mean s per stratum)", "",
              "| stratum | cheap | strong |", "|---|---|---|"]
    for s in STRATA:
        cells = []
        for tier in ("cheap", "strong"):
            vs = [verdict_of[(r["pair_id"], tier)] for r in by_stratum.get(s, [])
                  if (r["pair_id"], tier) in verdict_of]
            if vs:
                mc = sum(v["corr"] for v in vs) / len(vs)
                mi = sum(v["int"] for v in vs) / len(vs)
                ms = sum(v["corr"] * v["int"] for v in vs) / len(vs)
                cells.append(f"{mc:.2f} / {mi:.2f} / {ms:.2f}")
            else:
                cells.append("n/a")
        lines.append(f"| {s} | {cells[0]} | {cells[1]} |")
    lines.append("")

    both = [(r, verdict_of.get((r["pair_id"], "cheap")), verdict_of.get((r["pair_id"], "strong")))
            for r in pairs]
    both = [(r, c, g) for r, c, g in both if c and g]
    if both:
        lines += ["## Cheap/strong agreement (no labels needed)", ""]
        for axis in ("corr", "int"):
            kp = kappa([(int(c[axis] >= 0.5), int(g[axis] >= 0.5)) for _, c, g in both])
            lines.append(f"- {axis}: kappa (both binarised at 0.5) = "
                         f"{kp:.3f} on {len(both)} pairs" if kp is not None else
                         f"- {axis}: kappa undefined")
        lines.append("")

    if not labels:
        lines += [
            "## Pending",
            "",
            "Curator labels are not yet present, so confusion matrices, kappa "
            "against the curator, AUC, and the threshold sweep are pending. "
            "Fill in `labels_curator.jsonl` (binary `corr_label` and "
            "`int_label` per pair) and re-run this script.",
            "",
        ]
    else:
        good = {pid for pid, l in labels.items()
                if l["corr_label"] == 1 and l["int_label"] == 1}
        lines += ["## Judge vs curator", ""]
        for tier in ("cheap", "strong"):
            lines.append(f"### {tier} judge")
            lines.append("")
            for axis, lab in (("corr", "corr_label"), ("int", "int_label")):
                obs = [(verdict_of[(pid, tier)][axis], labels[pid][lab])
                       for pid in labels if (pid, tier) in verdict_of]
                kp = kappa([(int(s >= 0.5), y) for s, y in obs])
                a = auc(obs)
                kp_s = f"{kp:.3f}" if kp is not None else "undefined"
                a_s = f"{a:.3f}" if a is not None else "undefined"
                lines.append(f"- {axis}: kappa = {kp_s}, AUC = {a_s}, n = {len(obs)}")
            lines.append("")

        lines += ["## Threshold sweep (cheap judge, s = corr * int)", "",
                  "| threshold | recall on good | flagged share (random stratum) |",
                  "|---|---|---|"]
        random_ids = [r["pair_id"] for r in by_stratum.get("random", [])
                      if (r["pair_id"], "cheap") in verdict_of]
        chosen = None
        for t in [round(0.05 * k, 2) for k in range(0, 20)]:
            flagged_good = sum(
                1 for pid in good
                if (pid, "cheap") in verdict_of
                and verdict_of[(pid, "cheap")]["corr"] * verdict_of[(pid, "cheap")]["int"] >= t)
            n_good = sum(1 for pid in good if (pid, "cheap") in verdict_of)
            flagged_rand = sum(
                1 for pid in random_ids
                if verdict_of[(pid, "cheap")]["corr"] * verdict_of[(pid, "cheap")]["int"] >= t)
            recall = flagged_good / n_good if n_good else 0.0
            share = flagged_rand / len(random_ids) if random_ids else 1.0
            lines.append(f"| {t:.2f} | {fmt_ci(flagged_good, n_good)} | "
                         f"{fmt_ci(flagged_rand, len(random_ids))} |")
            if recall >= RECALL_TARGET and share <= FLAG_SHARE_CAP:
                chosen = t if chosen is None or t > chosen else chosen
        lines.append("")
        if chosen is not None:
            lines.append(
                f"Chosen operating point: threshold {chosen:.2f} (largest with "
                f"point-estimate recall >= {RECALL_TARGET} and flagged share "
                f"<= {FLAG_SHARE_CAP:.0%}). The binding production check is "
                "the Phase 1 leak audit (Clopper-Pearson bound), not this "
                "point estimate.")
        else:
            lines.append(
                f"No operating point reaches recall >= {RECALL_TARGET} at "
                f"flagged share <= {FLAG_SHARE_CAP:.0%}: exercise the "
                "escalation rule in judges.yaml (promote the cheap tier) and "
                "re-measure.")
        lines.append("")

    failures = []
    for log in sorted((P3 / "logs").glob("judge-*.jsonl")):
        for row in load_jsonl(log):
            if row.get("error"):
                failures.append(row)
    lines += ["## Contract failures (from raw logs)", "",
              f"- {len(failures)} failed judge calls recorded in raw logs "
              "(retries included; final-state failures only appear if a pair "
              "still lacks a verdict above).", ""]

    lines += ["## Known limitations", "",
              "- Strata `surface_similar` and `hard_positive` are below plan "
              "targets (audit-derived seeds only); the curator extends them "
              "by hand before labels are final.",
              "- 7 vendor papers have no abstract (non-arXiv or API miss); "
              "their pairs are judged from titles, flagged via the "
              "`(not available; judge from the title)` placeholder.",
              "- Calibration precision is a calibration-only number; "
              "production precision comes from the Phase 1 random sample.",
              ""]

    REPORT_PATH.write_text("\n".join(lines))
    print(f"wrote {REPORT_PATH}")


if __name__ == "__main__":
    main()
