"""Regenerate pathfinder3/calibration/report.md from the ledger.

Reads ledger + calibration manifest and turns cheap/strong verdicts into a
model-referenced Phase 0 operating report. The stratum tables from the old
pathfinder1/2-taxonomy version are replaced by two segments: the random
subset (unbiased draw, used for the forwarding-rate rule) and all
calibration pairs. worked_example exclusions come from the manifest.

Primary calibration target is strong-model recall: choose a cheap threshold
that preserves pairs the strong judge would keep. The report is generated,
never hand-edited. See plans/pathfinder3-ledger-refactor-design.md.

Usage: python3 pathfinder3/scripts/calibration_report.py
"""
from __future__ import annotations

import math
from datetime import date

import ledger
from _common import P3

REPORT_PATH = P3 / "calibration" / "report.md"
RECALL_TARGET = 0.95
FLAG_SHARE_CAP = 0.10
STRONG_REFERENCE_SCORE = 0.25
AXIS_REFERENCE_SCORE = 0.50
THRESHOLDS = [round(0.05 * k, 2) for k in range(0, 20)]

CHEAP_JUDGE = "claude:claude-haiku-4-5"
STRONG_JUDGE = "claude:claude-opus-4-8"
CHEAP_PROMPT_VERSION = "v2"
STRONG_PROMPT_VERSION = "v2"


def wilson(successes: int, n: int, z: float = 1.96) -> tuple[float, float]:
    if n == 0:
        return (0.0, 1.0)
    p = successes / n
    denom = 1 + z * z / n
    centre = (p + z * z / (2 * n)) / denom
    half = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / denom
    return (max(0.0, centre - half), min(1.0, centre + half))


def kappa(pairs: list[tuple[int, int]]) -> float | None:
    n = len(pairs)
    if n == 0:
        return None
    po = sum(1 for a, b in pairs if a == b) / n
    pa1 = sum(a for a, _ in pairs) / n
    pb1 = sum(b for _, b in pairs) / n
    pe = pa1 * pb1 + (1 - pa1) * (1 - pb1)
    if pe == 1:
        return None
    return (po - pe) / (1 - pe)


def fmt_ci(successes: int, n: int) -> str:
    if n == 0:
        return "n/a"
    lo, hi = wilson(successes, n)
    return f"{successes / n:.3f} [{lo:.3f}, {hi:.3f}] ({successes}/{n})"


def eval_pair_ids(led: ledger.Ledger) -> set[str]:
    return {pid for pid, row in led.manifest.items() if not row["worked_example"]}


def random_pair_ids(led: ledger.Ledger) -> set[str]:
    return {pid for pid, row in led.manifest.items()
            if row["selection"]["method"] == "random"}


def _verdict(led: ledger.Ledger, pair_id: str, judge: str, prompt_version: str) -> dict | None:
    matches = [e for e in led.canonical_for_pair(pair_id)
               if e["judge"] == judge and e["prompt_version"] == prompt_version]
    return matches[0] if matches else None


def cheap_score(led: ledger.Ledger, pair_id: str) -> float | None:
    v = _verdict(led, pair_id, CHEAP_JUDGE, CHEAP_PROMPT_VERSION)
    return ledger.score(v) if v else None


def strong_score(led: ledger.Ledger, pair_id: str) -> float | None:
    v = _verdict(led, pair_id, STRONG_JUDGE, STRONG_PROMPT_VERSION)
    return ledger.score(v) if v else None


def strong_axis(led: ledger.Ledger, pair_id: str) -> tuple[float, float] | None:
    v = _verdict(led, pair_id, STRONG_JUDGE, STRONG_PROMPT_VERSION)
    return (v["corr"], v["int"]) if v else None


def strong_reference(led: ledger.Ledger, pair_id: str) -> bool:
    s = strong_score(led, pair_id)
    return s is not None and s >= STRONG_REFERENCE_SCORE


def strong_axis_reference(led: ledger.Ledger, pair_id: str) -> bool:
    axes = strong_axis(led, pair_id)
    return axes is not None and axes[0] >= AXIS_REFERENCE_SCORE and axes[1] >= AXIS_REFERENCE_SCORE


def main() -> None:
    led = ledger.load_ledger()
    eval_pairs = eval_pair_ids(led)
    random_pairs = random_pair_ids(led) & eval_pairs
    excluded_examples = sum(1 for r in led.manifest.values() if r["worked_example"])

    both = [(pid, cheap_score(led, pid), strong_score(led, pid)) for pid in eval_pairs]
    both = [(pid, c, s) for pid, c, s in both if c is not None and s is not None]

    lines = [
        "# Pathfinder3 calibration report", "",
        f"Generated by `calibration_report.py` on {date.today().isoformat()}; "
        "do not hand-edit. Sourced from the ledger + calibration manifest, "
        "not the pathfinder1/2 stratum taxonomy.", "",
        f"Calibration pairs: {len(led.manifest)}. Excluded worked examples: "
        f"{excluded_examples}. Evaluated: {len(eval_pairs)}.", "",
    ]

    if both:
        lines += ["## Cheap/strong agreement", ""]
        axis_pairs_corr, axis_pairs_int = [], []
        for pid, _c, _s in both:
            ca = _verdict(led, pid, CHEAP_JUDGE, CHEAP_PROMPT_VERSION)
            sa = _verdict(led, pid, STRONG_JUDGE, STRONG_PROMPT_VERSION)
            axis_pairs_corr.append((int(ca["corr"] >= 0.5), int(sa["corr"] >= 0.5)))
            axis_pairs_int.append((int(ca["int"] >= 0.5), int(sa["int"] >= 0.5)))
        kc, ki = kappa(axis_pairs_corr), kappa(axis_pairs_int)
        lines.append(f"- corr: kappa (both binarised at 0.5) = "
                     f"{kc:.3f} on {len(both)} pairs" if kc is not None else "- corr: kappa undefined")
        lines.append(f"- int: kappa (both binarised at 0.5) = "
                     f"{ki:.3f} on {len(both)} pairs" if ki is not None else "- int: kappa undefined")
        lines.append("")

    strong_ref = [pid for pid in eval_pairs
                  if strong_reference(led, pid) and cheap_score(led, pid) is not None]
    strong_axis_ref = [pid for pid in eval_pairs
                       if strong_axis_reference(led, pid) and cheap_score(led, pid) is not None]
    cheap_judged = [pid for pid in eval_pairs if cheap_score(led, pid) is not None]
    random_judged = [pid for pid in random_pairs if cheap_score(led, pid) is not None]

    recall_choice = budget_choice = None
    if strong_ref and cheap_judged:
        lines += [
            "## Model-referenced threshold sweep", "",
            f"Primary reference positive: any strong judge with "
            f"`s = corr * int >= {STRONG_REFERENCE_SCORE:.2f}`.", "",
            "| threshold | recall on strong reference | all calibration flagged | random flagged |",
            "|---|---|---|---|",
        ]
        for t in THRESHOLDS:
            flagged_ref = sum(1 for pid in strong_ref if (cheap_score(led, pid) or 0.0) >= t)
            flagged_all = sum(1 for pid in cheap_judged if (cheap_score(led, pid) or 0.0) >= t)
            flagged_rand = sum(1 for pid in random_judged if (cheap_score(led, pid) or 0.0) >= t)
            recall = flagged_ref / len(strong_ref)
            random_share = flagged_rand / len(random_judged) if random_judged else 1.0
            lines.append(f"| {t:.2f} | {fmt_ci(flagged_ref, len(strong_ref))} | "
                         f"{fmt_ci(flagged_all, len(cheap_judged))} | "
                         f"{fmt_ci(flagged_rand, len(random_judged))} |")
            if recall >= RECALL_TARGET:
                recall_choice = t if recall_choice is None or t > recall_choice else recall_choice
            if random_share <= FLAG_SHARE_CAP and budget_choice is None:
                budget_choice = t
        lines.append("")
        if recall_choice is not None:
            kept_all = sum(1 for pid in cheap_judged if (cheap_score(led, pid) or 0.0) >= recall_choice)
            kept_rand = sum(1 for pid in random_judged if (cheap_score(led, pid) or 0.0) >= recall_choice)
            lines.append(f"Recall-first operating point: threshold {recall_choice:.2f}. "
                         f"Forwards {kept_all}/{len(cheap_judged)} calibration pairs; "
                         f"random-subset forwarding is {fmt_ci(kept_rand, len(random_judged))}.")
        if budget_choice is not None:
            kept_ref = sum(1 for pid in strong_ref if (cheap_score(led, pid) or 0.0) >= budget_choice)
            lines.append(f"Budget checkpoint: threshold {budget_choice:.2f} is the "
                         f"lowest with random-subset forwarding <= {FLAG_SHARE_CAP:.0%}; "
                         f"recall {fmt_ci(kept_ref, len(strong_ref))}.")
        lines.append("")

        lines += ["### Reference sensitivity", "",
                  "| reference rule | positives | recall at recall-first threshold |",
                  "|---|---|---|"]
        threshold = recall_choice if recall_choice is not None else 0.0
        for name, refs in ((f"strong s >= {STRONG_REFERENCE_SCORE:.2f}", strong_ref),
                           (f"strong corr >= {AXIS_REFERENCE_SCORE:.2f} and int >= "
                            f"{AXIS_REFERENCE_SCORE:.2f}", strong_axis_ref)):
            if not refs:
                lines.append(f"| {name} | 0 | n/a |")
                continue
            kept = sum(1 for pid in refs if (cheap_score(led, pid) or 0.0) >= threshold)
            lines.append(f"| {name} | {len(refs)} | {fmt_ci(kept, len(refs))} |")
        lines.append("")

    REPORT_PATH.write_text("\n".join(lines))
    print(f"wrote {REPORT_PATH}")


if __name__ == "__main__":
    main()
